name: firebase_authentication
description: A Flutter package to simplify firebase authentication.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # AUTH SERVICES
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  sign_in_with_apple: ^3.0.0
  flutter_twitter_login: ^1.1.0
  firebase_dynamic_links: ^2.0.7

  crypto: ^3.0.1

  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  freezed: ^0.14.2

flutter:
